todo_application/todo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('my_todo/', views.index, name='index'),
]

todo_application/todo_application/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("todo/", include("todo.urls")),
]

todo_application/todo/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager


class Task(models.Model):
    STATES = [
        ("1", "انجام نشده"),
        ("2", "در حال انجام"),
        ("3", "انجام شده"),
    ]
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="ایجاد کننده", on_delete=models.PROTECT)
    title = models.CharField("عنوان", max_length=200)
    description = models.TextField("شرح")
    state = models.CharField("وضعیت", max_length=30, choices=STATES, default="")
    creation_date = models.DateTimeField("تاریخ ایجاد", auto_now_add=True)
    due_date = models.DateField("تاریخ انجام", blank=True, null=True)
    last_modified = models.DateTimeField("آخرین بروز رسانی", auto_now=True, blank=True, null=True)
    tags = TaggableManager()
    is_active = models.BooleanField("فعال", default=True)

    class Meta:
        verbose_name = "تسک"
        verbose_name_plural = "تسک ها"

    def modify(self):
        self.modified_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

todo_application/todo/views.py
from django.shortcuts import render
from todo.models import *

def index(request):
    context = {}
    tasks = Task.objects.all()
    context.update({'tasks': tasks})
    return render(request, "index.html", context)

todo_application/todo/templates/index.html
<!doctype html>
<html lang="en">
  {% load static %}
  {% load date_converter %}
  <head>
  	<title>تسک ها</title>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'todo/bootstrap/css/min.css' %}">
    <link rel="stylesheet" href="{% static 'todo/bootstrap/js/bundle.min.js' %}">
    <link rel="stylesheet" href="{% static 'todo/ajax/js/jquery.min.js' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'todo/css/style.css' %}">
  </head>
<body>
<div class="row d-flex justify-content-center container">
    <div class="col-md-8">
      <div class="card-hover-shadow-2x mb-3 card">
        <div dir="rtl" class="card-header-tab card-header">
          <div dir="rtl" class="card-header-title font-size-lg text-capitalize font-weight-normal">
            <i class="fa fa-tasks"></i>&nbsp;لیست تسک ها</div>
          
        </div>
        <div class="scroll-area-sm">
          <perfect-scrollbar class="ps-show-limits">
            <div style="position: static;" class="ps ps--active-y">
              <div class="ps-content">
                <ul class=" list-group list-group-flush">
                  {% for task in tasks %}
                  <li class="list-group-item">
                    <div class="todo-indicator bg-warning"></div>
                    <div class="widget-content p-0">
                      <div class="widget-content-wrapper">
                        <div class="widget-content-left mr-2">
                        </div>
                        <div class="widget-content-left">
                          {% if task.state == '3' %}
                            <div class="widget-heading" style="text-decoration: line-through;">عنوان: {{ task.title }}<div class="badge badge-danger ml-2">{{ task.get_state_display }}</div>
                          {% else %}
                          <div class="widget-heading">عنوان: {{ task.title }}<div class="badge badge-danger ml-2">{{ task.get_state_display }}</div>
                          {% endif %}
                          </div>
                          <div class="widget-subheading"><i>شرح: {{ task.description }}</i></div>
                          <!-- <div class="widget-subheading"><i>برچسب(ها): {{ task.tags }}</i></div> -->
                          <div class="widget-subheading"><i>تاریخ ایجاد: {{ task.creation_date|jalali_date_time_convertor }}</i></div>
                          <div class="widget-subheading"><i>تاریخ انجام: {{ task.due_date|jalali_date_convertor }}</i></div>
                          <div class="widget-subheading"><i>آخرین بروز رسانی: {{ task.last_modified|jalali_date_time_convertor }}</i></div>
                          <div class="widget-subheading"><i>ایجاد شده توسط: {{ task.creator }}</i></div>
                        </div>
                      <div class="widget-content-right">
                        <button class="border-0 btn-transition btn btn-outline-success">
                          <i class="fa fa-check"></i></button>
                          <button class="border-0 btn-transition btn btn-outline-danger">
                         <i class="fa fa-trash"></i>
                        </button>
                      </div>
                      </div>
                    </div>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </perfect-scrollbar>
        </div>
        <div class="d-block text-right card-footer"><a href="{% url 'logout' %}" class="mr-2 btn btn-link btn-sm">خروج</a>
          <button class="btn btn-primary">افزودن تسک</button></div>
      </div>
    </div>
</div>
</body>
</html>

todo_application/todo/templates/mani_template.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
  	<title>تسک ها</title>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'todo/bootstrap/css/min.css' %}">
    <link rel="stylesheet" href="{% static 'todo/bootstrap/js/bundle.min.js' %}">
    <link rel="stylesheet" href="{% static 'todo/ajax/js/jquery.min.js' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'todo/css/style.css' %}">
  </head>
<body>
<div class="row d-flex justify-content-center container">
    <div class="col-md-8">
      <div class="card-hover-shadow-2x mb-3 card">
        <div dir="rtl" class="card-header-tab card-header">
          <div dir="rtl" class="card-header-title font-size-lg text-capitalize font-weight-normal">
            <i class="fa fa-tasks"></i>&nbsp;لیست تسک ها</div>
          
        </div>
        <div class="scroll-area-sm">
          <perfect-scrollbar class="ps-show-limits">
            <div style="position: static;" class="ps ps--active-y">
              <div class="ps-content">
                <ul class=" list-group list-group-flush">
                  <li class="list-group-item">
                    <div class="todo-indicator bg-warning"></div>
                    <div class="widget-content p-0">
                      <div class="widget-content-wrapper">
                        <div class="widget-content-left mr-2">
                          <div class="custom-checkbox custom-control">
                            <input class="custom-control-input"
                              id="exampleCustomCheckbox12" type="checkbox"><label class="custom-control-label"
                              for="exampleCustomCheckbox12">&nbsp;</label>
                            </div>
                        </div>
                        <div class="widget-content-left">
                          <div class="widget-heading">Call Sam For payments <div class="badge badge-danger ml-2">رد شده</div>
                          </div>
                          <div class="widget-subheading"><i>By Bob</i></div>
                        </div>
                      <div class="widget-content-right">
                        <button class="border-0 btn-transition btn btn-outline-success">
                          <i class="fa fa-check"></i></button>
                          <button class="border-0 btn-transition btn btn-outline-danger">
                         <i class="fa fa-trash"></i>
                         
                        </button>
                      </div>
                      </div>
                    </div>
                  </li>
                  <li class="list-group-item">
                    <div class="todo-indicator bg-focus"></div>
                    <div class="widget-content p-0">
                      <div class="widget-content-wrapper">
                        <div class="widget-content-left mr-2">
                          <div class="custom-checkbox custom-control"><input class="custom-control-input"
                              id="exampleCustomCheckbox1" type="checkbox"><label class="custom-control-label"
                              for="exampleCustomCheckbox1">&nbsp;</label></div>
                        </div>
                        <div class="widget-content-left">
                          <div class="widget-heading">Make payment to Bluedart</div>
                          <div class="widget-subheading">
                            <div>By Johnny <div class="badge badge-pill badge-info ml-2">جدید</div>
                            </div>
                            
                          </div>
                          
                        </div>
                        <div class="widget-content-right">
                          <button class="border-0 btn-transition btn btn-outline-success">
                            <i class="fa fa-check"></i></button>
                          <button class="border-0 btn-transition btn btn-outline-danger">
                            <i class="fa fa-trash"></i>
                        
                          </button>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li class="list-group-item">
                    <div class="todo-indicator bg-primary"></div>
                    <div class="widget-content p-0">
                      <div class="widget-content-wrapper">
                        <div class="widget-content-left mr-2">
                          <div class="custom-checkbox custom-control"><input class="custom-control-input"
                              id="exampleCustomCheckbox4" type="checkbox"><label class="custom-control-label"
                              for="exampleCustomCheckbox4">&nbsp;</label></div>
                        </div>
                        <div class="widget-content-left flex2">
                          <div class="widget-heading">Office rent </div>
                          <div class="widget-subheading">By Samino!</div>
                        </div>
                        
                        <div class="widget-content-right">
                          <button class="border-0 btn-transition btn btn-outline-success">
                            <i class="fa fa-check"></i></button>
                          <button class="border-0 btn-transition btn btn-outline-danger">
                            <i class="fa fa-trash"></i>
                        
                          </button>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li class="list-group-item">
                    <div class="todo-indicator bg-info"></div>
                    <div class="widget-content p-0">
                      <div class="widget-content-wrapper">
                        <div class="widget-content-left mr-2">
                          <div class="custom-checkbox custom-control"><input class="custom-control-input"
                              id="exampleCustomCheckbox2" type="checkbox"><label class="custom-control-label"
                              for="exampleCustomCheckbox2">&nbsp;</label></div>
                        </div>
                        
                        <div class="widget-content-left">
                          <div class="widget-heading">Office grocery shopping</div>
                          <div class="widget-subheading">By Tida</div>
                        </div>
                        <div class="widget-content-right">
                          <button class="border-0 btn-transition btn btn-outline-success">
                            <i class="fa fa-check"></i></button>
                          <button class="border-0 btn-transition btn btn-outline-danger">
                            <i class="fa fa-trash"></i>
                        
                          </button>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li class="list-group-item">
                    <div class="todo-indicator bg-success"></div>
                    <div class="widget-content p-0">
                      <div class="widget-content-wrapper">
                        <div class="widget-content-left mr-2">
                          <div class="custom-checkbox custom-control"><input class="custom-control-input"
                              id="exampleCustomCheckbox3" type="checkbox"><label class="custom-control-label"
                              for="exampleCustomCheckbox3">&nbsp;</label></div>
                        </div>
                        <div class="widget-content-left flex2">
                          <div class="widget-heading">Ask for Lunch to Clients</div>
                          <div class="widget-subheading">By Office Admin</div>
                        </div>
                        
                        <div class="widget-content-right">
                          <button class="border-0 btn-transition btn btn-outline-success">
                            <i class="fa fa-check"></i></button>
                          <button class="border-0 btn-transition btn btn-outline-danger">
                            <i class="fa fa-trash"></i>
                        
                          </button>
                        </div>
                      </div>
                    </div>
                  </li>

                  <li class="list-group-item">
                    <div class="todo-indicator bg-success"></div>
                    <div class="widget-content p-0">
                      <div class="widget-content-wrapper">
                        <div class="widget-content-left mr-2">
                          <div class="custom-checkbox custom-control"><input class="custom-control-input" id="exampleCustomCheckbox10"
                              type="checkbox"><label class="custom-control-label" for="exampleCustomCheckbox10">&nbsp;</label></div>
                        </div>
                        <div class="widget-content-left flex2">
                          <div class="widget-heading">Client Meeting at 11 AM</div>
                          <div class="widget-subheading">By CEO</div>
                        </div>
                  
                        <div class="widget-content-right">
                          <button class="border-0 btn-transition btn btn-outline-success">
                            <i class="fa fa-check"></i></button>
                          <button class="border-0 btn-transition btn btn-outline-danger">
                            <i class="fa fa-trash"></i>
                  
                          </button>
                        </div>
                      </div>
                    </div>
                  </li>
                </ul>
              </div>
              
            </div>
          </perfect-scrollbar>
        </div>
        <div class="d-block text-right card-footer"><button class="mr-2 btn btn-link btn-sm">Cancel</button><button
            class="btn btn-primary">Add Task</button></div>
      </div>
    </div>
</div>
</body>
</html>